apiVersion: 1

datasources:
  - name: Prometheus
    uid: 1
    access: proxy
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
  - name: Tibber exporter
    uid: 2
    access: proxy
    type: yesoreyeram-infinity-datasource
    url: http://tibber-exporter:8080
    isDefault: false
